name: Build App

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - release
      - dev

env:
  # Our build metadata
  BUILD_USER: android-builder
  BUILD_HOST: github.ajmalshajahan.me

jobs:
  build:
    name: Debug Build
    runs-on: ubuntu-latest
    container: ghcr.io/ajmalshajahan/syncthing-android-builder
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
        with:
          submodules: true
          fetch-depth: 0

      - name: build
        run: |
          git config --system --add safe.directory '*'
          java -version
          ./gradlew --no-daemon buildNative lint assembleDebug

      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: syncthing-android-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk

      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: reports-and-libs
          path: |
            app/build/reports/**
            app/src/main/jniLibs/**
